namespace ModbusTCP;

[Flags]
public enum ModbusFunction : byte
{
    READ_COIL = 1,
    READ_DISCRETE_INPUTS = 2,
    READ_HOLDING_REGISTER = 3,
    READ_INPUT_REGISTER = 4,
    WRITE_SINGLE_COIL = 5,
    WRITE_SINGLE_REGISTER = 6,
    WRITE_MULTIPLE_COILS = 15,
    WRITE_MULTIPLE_REGISTER = 16,
    READ_WRITE_MULTIPLE_REGISTER = 23,
    READ_DEVICE_IDENTIFIERS = 0x2b,
    EXCEPTION = 128,
    INVALID = 0xFF
}
